[package]
name = "day-10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
commons = { path = "../commons" }
thiserror = "1.0.30"
lazy_static = "1.4.0"
itertools = "0.10.3"
